<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="131" started-at="2018-06-08T19:45:27Z" finished-at="2018-06-08T19:45:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="131" started-at="2018-06-08T19:45:27Z" finished-at="2018-06-08T19:45:28Z">
      <class name="pe.com.test.semana10.AdministradorServiceTest">
        <test-method status="FAIL" signature="ProbandoModeloAdmistrador()[pri:0, instance:pe.com.test.semana10.AdministradorServiceTest@715a70e9]" name="ProbandoModeloAdmistrador" duration-ms="34" started-at="2018-06-08T19:45:28Z" finished-at="2018-06-08T19:45:28Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at pe.com.test.semana10.AdministradorServiceTest.ProbandoModeloAdmistrador(AdministradorServiceTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProbandoModeloAdmistrador -->
        <test-method status="PASS" signature="contextLoads()[pri:0, instance:pe.com.test.semana10.AdministradorServiceTest@715a70e9]" name="contextLoads" duration-ms="14" started-at="2018-06-08T19:45:28Z" finished-at="2018-06-08T19:45:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contextLoads -->
      </class> <!-- pe.com.test.semana10.AdministradorServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
